package communication;

public enum RESPONSE_ID {
    SUCCESS,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    NO_DATA,
    INSERT_SUCCESS,
    INSERT_FAILED,
    UPDATE_SUCCESS,
    UPDATE_FAILED,
    DELETE_SUCCESS,
    DELETE_FAILED
}
